export const MINECRAFT_CLIMATE_VARIANCE_STRETCH = 2.2
export const MINECRAFT_CLIMATE_MIN = 0
export const MINECRAFT_CLIMATE_MAX = 1
export const MINECRAFT_CLIMATE_CENTER = 0.5

export const MINECRAFT_PV_BASE = 1
export const MINECRAFT_PV_WEIRDNESS_SCALE = 3
export const MINECRAFT_PV_WEIRDNESS_OFFSET = 2

export const MINECRAFT_TEMP_COLD = 0.3
export const MINECRAFT_TEMP_HOT = 0.7

export const MINECRAFT_HUM_DRY = 0.3
export const MINECRAFT_HUM_WET = 0.6
export const MINECRAFT_HUM_VERY_DRY = 0.15
export const MINECRAFT_HUM_VERY_WET = 0.85
export const MINECRAFT_HUM_JUNGLE = 0.72
export const MINECRAFT_TEMP_JUNGLE = 0.78
export const MINECRAFT_HUM_TAIGA = 0.55
export const MINECRAFT_HUM_MOUNTAINS = 0.4
export const MINECRAFT_HUM_SAVANNA_MIN = 0.22

export const MINECRAFT_RIVER_NOISE_SCALE = 0.0035
export const MINECRAFT_RIVER_WORLD_OFFSET = 20_000
export const MINECRAFT_RIVER_CENTER = 0.5
export const MINECRAFT_RIVER_HALF_WIDTH = 0.02

export const MINECRAFT_CONTINENTALNESS_RIVER_MIN = -0.22
export const MINECRAFT_CONTINENTALNESS_RIVER_MAX = 0.42
export const MINECRAFT_CONTINENTALNESS_OCEAN_MAX = -0.42
export const MINECRAFT_CONTINENTALNESS_MOUNTAIN_MIN = 0.32
export const MINECRAFT_CONTINENTALNESS_SWAMP_FOREST_MIN = 0.35
export const MINECRAFT_MOUNTAININESS_MOUNTAIN_MIN = 0.32
export const MINECRAFT_MOUNTAININESS_TAIGA_MAX = 0.28
export const MINECRAFT_MOUNTAININESS_PV_WEIGHT = 0.65
export const MINECRAFT_MOUNTAININESS_EROSION_WEIGHT = 0.35
export const MINECRAFT_MOUNTAININESS_EROSION_BASELINE = 0.45
export const MINECRAFT_EROSION_FOREST_MAX = 0.15
export const MINECRAFT_RIVER_FLOWER_FOREST_MIN = 0.8
export const MINECRAFT_BEACH_CONTINENTALNESS_MAX = 0.12

