const HALF = 0.5
const ONE = 1
const TWO = 2
const THREE = 3
const FOUR = 4
const SIX = 6
const SEVEN = 7

export const SIMPLEX_ZERO = 0
export const SIMPLEX_ONE: number = ONE
export const SIMPLEX_TWO: number = TWO
export const SIMPLEX_THREE: number = THREE
export const SIMPLEX_FOUR: number = FOUR
export const SIMPLEX_SIX: number = SIX
export const SIMPLEX_SEVEN: number = SEVEN
export const SIMPLEX_NEGATIVE_ONE: number = -ONE
export const SIMPLEX_HALF: number = HALF
export const SIMPLEX_GRADIENT_COUNT = 16
export const SIMPLEX_GRADIENT_MASK: number = SIMPLEX_GRADIENT_COUNT - ONE
export const SIMPLEX_RANK_MASK: number = SEVEN
export const SIMPLEX_X_INDEX: number = SIMPLEX_ZERO
export const SIMPLEX_Y_INDEX: number = SIMPLEX_ONE
export const SIMPLEX_Z_INDEX: number = SIMPLEX_TWO
export const SIMPLEX_CONTRIBUTION_POWER: number = FOUR
export const SIMPLEX_PERMUTATION_MASK = 255
export const SIMPLEX_SKEW_2D: number = HALF * (Math.sqrt(THREE) - ONE)
export const SIMPLEX_UNSKEW_2D: number = (THREE - Math.sqrt(THREE)) / SIX
export const SIMPLEX_TWO_UNSKEW_2D: number = TWO * SIMPLEX_UNSKEW_2D
export const SIMPLEX_SKEW_3D: number = ONE / THREE
export const SIMPLEX_UNSKEW_3D: number = ONE / SIX
export const SIMPLEX_TWO_UNSKEW_3D: number = TWO * SIMPLEX_UNSKEW_3D
export const SIMPLEX_THREE_UNSKEW_3D: number = THREE * SIMPLEX_UNSKEW_3D
export const SIMPLEX_RADIUS_2D: number = HALF
export const SIMPLEX_RADIUS_3D = 0.6
export const SIMPLEX_SCALE_2D = 70
export const SIMPLEX_SCALE_3D = 32
