const HALF = 0.5
const ONE = 1
const TWO = 2
const THREE = 3
const FOUR = 4
const SIX = 6
const SEVEN = 7

export const SIMPLEX_ZERO = 0
export const SIMPLEX_ONE = ONE
export const SIMPLEX_TWO = TWO
export const SIMPLEX_THREE = THREE
export const SIMPLEX_FOUR = FOUR
export const SIMPLEX_SIX = SIX
export const SIMPLEX_SEVEN = SEVEN
export const SIMPLEX_NEGATIVE_ONE = -ONE
export const SIMPLEX_HALF = HALF
export const SIMPLEX_GRADIENT_COUNT = 16
export const SIMPLEX_GRADIENT_MASK = SIMPLEX_GRADIENT_COUNT - ONE
export const SIMPLEX_RANK_MASK = SEVEN
export const SIMPLEX_X_INDEX = SIMPLEX_ZERO
export const SIMPLEX_Y_INDEX = SIMPLEX_ONE
export const SIMPLEX_Z_INDEX = SIMPLEX_TWO
export const SIMPLEX_CONTRIBUTION_POWER = FOUR
export const SIMPLEX_PERMUTATION_MASK = 255
export const SIMPLEX_SKEW_2D = HALF * (Math.sqrt(THREE) - ONE)
export const SIMPLEX_UNSKEW_2D = (THREE - Math.sqrt(THREE)) / SIX
export const SIMPLEX_TWO_UNSKEW_2D = TWO * SIMPLEX_UNSKEW_2D
export const SIMPLEX_SKEW_3D = ONE / THREE
export const SIMPLEX_UNSKEW_3D = ONE / SIX
export const SIMPLEX_TWO_UNSKEW_3D = TWO * SIMPLEX_UNSKEW_3D
export const SIMPLEX_THREE_UNSKEW_3D = THREE * SIMPLEX_UNSKEW_3D
export const SIMPLEX_RADIUS_2D = HALF
export const SIMPLEX_RADIUS_3D = 0.6
export const SIMPLEX_SCALE_2D = 70
export const SIMPLEX_SCALE_3D = 32
